-- MySQL Script generated by MySQL Workbench
-- 02/15/15 10:50:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema regatta
-- -----------------------------------------------------
DROP SCHEMA `regatta`;

-- -----------------------------------------------------
-- Schema regatta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `regatta` ;
USE `regatta` ;

-- -----------------------------------------------------
-- Table `regatta`.`Boat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regatta`.`Boat` (
  `idBoat` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idBoat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regatta`.`Regatta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regatta`.`Regatta` (
  `idRegatta` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idRegatta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regatta`.`Teammate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regatta`.`Teammate` (
  `idTeammate` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeammate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regatta`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regatta`.`Team` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Boat_idBoat` INT NOT NULL,
  PRIMARY KEY (`idTeam`, `Boat_idBoat`),
  INDEX `fk_Team_Boat_idx` (`Boat_idBoat` ASC),
  CONSTRAINT `fk_Team_Boat`
    FOREIGN KEY (`Boat_idBoat`)
    REFERENCES `regatta`.`Boat` (`idBoat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regatta`.`Inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regatta`.`Inscription` (
  `Regatta_idRegatta` INT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`Regatta_idRegatta`, `Team_idTeam`),
  INDEX `fk_Inscription_Team1_idx` (`Team_idTeam` ASC),
  CONSTRAINT `fk_Inscription_Regatta1`
    FOREIGN KEY (`Regatta_idRegatta`)
    REFERENCES `regatta`.`Regatta` (`idRegatta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscription_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `regatta`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regatta`.`TeamComposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regatta`.`TeamComposition` (
  `Teammate_idTeammate` INT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`Teammate_idTeammate`, `Team_idTeam`),
  INDEX `fk_TeamComposition_Teammate1_idx` (`Teammate_idTeammate` ASC),
  INDEX `fk_TeamComposition_Team1_idx` (`Team_idTeam` ASC),
  CONSTRAINT `fk_TeamComposition_Teammate1`
    FOREIGN KEY (`Teammate_idTeammate`)
    REFERENCES `regatta`.`Teammate` (`idTeammate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TeamComposition_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `regatta`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
